### ISSUE TITLE
Serve via CDN

### ISSUE THREAD

**Issue by mtvbrianking** [imhvost/chart-utils#1]
Hi @imhvost,

Do you have hopes of serving this via CDN

For quick tests (via Codepen) the GitHub raw link won't work.

While copying the content into Codepen works just fine, it an overkill.

Serving the JS file via GitHub pages should work just as fine.

**Comment by imhvost** [comment]
@mtvbrianking Hello! Thanks for the comment! Made here:
[https://imhvost.github.io/chart-utils.min.js](https://imhvost.github.io/chart-utils.min.js)
